const ROOT = 'view/feature';
export const FETCH_USER_REQUEST = `${ROOT}/FETCH_USER_REQUEST`;
export const FETCH_USER_SUCCESS = `${ROOT}/FETCH_USER_SUCCESS`;
export const FETCH_USER_FAILURE = `${ROOT}/FETCH_USER_FAILURE`;
